# Favicon
favicon: /favicon.ico

# SEO
keywords: 
  - Sooham
  - Rafiz
  - Computer
  - Science
  - Engineer
  - Data-Structures
  - Google
  - Intel
  - Amazon
  - Apple
  - Big-N
  - Technology

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  Blog: /archives
  GitHub: https://github.com/sooham
  Linkedin: www.linkedin.com/in/sooham-rafiz

# Google Analytics (GA4)
# Get your measurement ID from: https://analytics.google.com
google_analytics: G-WC8766BHKN

# Nav menu
menu:
  Home: /
  #Archives: /archives
  #About: /about
