# Favicon
favicon: /favicon.ico

# SEO
keywords: 
  - Sooham
  - Rafiz
  - Computer
  - Science
  - Engineer
  - Data-Structures
  - Google
  - Intel
  - Amazon
  - Apple
  - Big-N
  - Technology

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config (social links - used in footer)
sns:
  GitHub: https://github.com/sooham
  LinkedIn: https://www.linkedin.com/in/sooham-rafiz

# Google Analytics (GA4)
# Get your measurement ID from: https://analytics.google.com
google_analytics: G-WC8766BHKN

# Nav menu (used in header partial)
menu:
  About: /
  Blog: /archives
  Visualizations: /visualizations
